// data-testid registry
export const DASHBOARD = {
  root: "dashboard-root",
  monthPrev: "month-prev-btn",
  monthNext: "month-next-btn",
  monthLabel: "month-current-label",
  yearLabel: "year-current-label",
  addBilling: "add-billing-btn",
  addExpense: "add-expense-btn",
  summaryIncome: "summary-income",
  summaryExpense: "summary-expense",
  summaryBalance: "summary-balance",
  summaryCommitted: "summary-committed",
  billingList: "billing-list",
  billingItem: (id) => `billing-item-${id}`,
  billingDelete: (id) => `billing-delete-${id}`,
  billingDeleteAll: (id) => `billing-delete-all-${id}`,
  expenseList: "expense-list",
  expenseItem: (id) => `expense-item-${id}`,
  expenseDelete: (id) => `expense-delete-${id}`,
  expenseDeleteAll: (id) => `expense-delete-all-${id}`,
  expenseToggleStatus: (id) => `expense-toggle-status-${id}`,
  expenseEdit: (id) => `expense-edit-${id}`,
  chart: "spending-chart",
};

export const MODAL = {
  billingDialog: "billing-modal",
  billingName: "billing-name-input",
  billingType: "billing-type-select",
  billingValue: "billing-value-input",
  billingSubmit: "billing-submit-btn",
  billingCancel: "billing-cancel-btn",
  expenseDialog: "expense-modal",
  expenseName: "expense-name-input",
  expenseType: "expense-type-select",
  expenseValue: "expense-value-input",
  expenseStatus: "expense-status-select",
  expenseSubmit: "expense-submit-btn",
  expenseCancel: "expense-cancel-btn",
};
